### PR TITLE
Thefootest patch 3

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by emailbob** [comment]
Can one of the admins verify this patch?

**Comment by emailbob** [comment]
add to whitelist

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
this is a test one

**Comment by emailbob** [comment]
test this please

**Comment by ghost** [comment]
test this please

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
watch

**Comment by ghost** [comment]
test this please

**Comment by emailbob** [comment]
add to whitelist

**Pull request closed without merging**
